ott_table:
  _target_: dpr.data.retriever_data.MyJsonlTablesCtxSrc
  file: /mnt/sdd/shpark/cos/knowledge/ott_table_chunks_original.json
  id_prefix: 'ott-original:'

ott_wiki_passages:
  _target_: dpr.data.retriever_data.MyJsonlTablesCtxSrc
  file: /mnt/sdd/shpark/cos/knowledge/ott_wiki_passages.json
  id_prefix: 'ott-wiki:'